package com.sentinelvoice.audit;

public enum AuditEventType {
    SESSION_OPENED,
    FEATURE_FRAME_SCORED,
    RISK_LEVEL_CHANGED,
    INTERVENTION_ACTION_FIRED,
    ANALYST_OVERRIDE,
    CHALLENGE_ISSUED,
    CHALLENGE_RESULT,
    PASSPORT_ENROLLED,
    PASSPORT_ERASED,
    TRANSCRIPT_BREAK_GLASS_ACCESS,
    DOSSIER_GENERATED,
    SESSION_CLOSED
}
