spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sentinelvoice
    driver-class-name: org.postgresql.Driver
    username: sentinel
    password: sentinel
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update